on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: mheap/portal-sync-action@v1
        with:
          konnect_pat: ${{ secrets.KONNECT_PAT }}
